Repository nonsoolmate/NONSOOLMATE-SERVER, pull requests merged in 2024-01, with the labels that each got.

#33 [FEAT] 목표대학 조회 API 개발
  nonsoolmateServer/.gitignore
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/dto/response/MemberAuthResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/service/AuthService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/MyController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dto/response/NameResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dto/response/TicketResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/exception/MemberSuccessType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/service/MemberService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/service/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/SelectUniversityController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/dto/response/SelectUniversityResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/exception/SelectUniversityException.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/exception/SelectUniversityExceptionType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/exception/SelectUniversitySuccessType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/exception/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/repository/SelectUniversityRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/repository/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityExamController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dto/UniversityExamInfoResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/UniversityExam.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamException.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamExceptionType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamSuccessType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/UniversityExamRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/UniversityRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/dummy.txt
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/oauth/service/NaverAuthService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/GlobalExceptionHandler.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/AuthUser.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/CustomAuthUser.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java
  nonsoolmateServer/src/main/resources/init/data.sql
  nonsoolmateServer/src/main/resources/init/schema.sql
Labels: feat

#34 [FEAT] 시험 보기: 문제지 조회 API 개발
  nonsoolmateServer/.gitignore
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityExamController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dto/UniversityExamImageResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamSuccessType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/UniversityExamImageRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
Labels: euna, feat

#45 [FIX] 목표대학 DTO 값 변경
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/dto/response/SelectUniversityResponseDTO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
Labels: song, fix

#81 [FIX] 대학 시험 이름에 대학교 이름 + 시험 년도 포함되도록 수정
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
Labels: fix

#87 [REFACTOR] 공통 메서드를 entity내 메서드로 수정
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/UniversityExam.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/service/UniversityExamRecordService.java
Labels: feat, song

#96 [REFACTOR] 목표대학 삭제 및 추가 로직 메서드 분리
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
Labels: song, refactor

#103 [FIX] 플랫폼 타입 검증 오류 수정
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/entity/enums/PlatformType.java
Labels: song, fix

#111 [FIX] SwaggerConfig에 https 설정 추가
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/swagger/config/SwaggerConfig.java
Labels: euna, fix

#116 [FIX] corsFilter 삭제
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java
Labels: euna, fix

#120 [FEAT] error 컨트롤러 구현
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthController.java
Labels: euna, feat

#127 [MOVE] 스웨거 폴더 위치 변경
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/swagger/config/SwaggerConfig.java
Labels: song, move

#129 [FEAT] Bearer 토큰 내용 오류 예외 처리 추가
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/filter/JwtAuthenticationFilter.java
Labels: feat, song

#134 [FIX] getUniversityExamName -> getUniversityExamFullName 변경
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
Labels: euna, fix
